profiler: Expose missing profile stacks count as a prometheus metric
parca-dev/parca-agent pull request #237
Opened 2022-02-14 11:12 UTC by Sylfrena

Signed-off-by: Sumera Priyadarsini <sylphrenadin@gmail.com>

2022-02-14 12:56 UTC, kakkoyun reviewed
Looking good. 
I have pointed out a couple of minor things.

2022-02-14 12:56 UTC, kakkoyun commented on cmd/parca-agent/main.go
> +			return tm.Run(ctx, m.SyncCh(), reg)
Better to move passing the registry to the constructor.

2022-02-16 13:42 UTC, kakkoyun requested changes
Looking great!

Just pointed out some name things.

2022-02-16 13:42 UTC, kakkoyun commented on cmd/parca-agent/main.go
> +	tm := target.NewManager(logger, reg, externalLabels, ksymCache, listener, dc, flags.ProfilingDuration, flags.TempDir)
👍

2022-02-16 13:42 UTC, kakkoyun commented on pkg/profiler/profiler.go
> +			[]string{"stacktype"}),
```suggestion
			[]string{"type"}),
```

2022-02-16 13:42 UTC, kakkoyun commented on pkg/profiler/profiler.go
> +			p.missingStacks.WithLabelValues("userstack").Inc()
```suggestion
			p.missingStacks.WithLabelValues("user").Inc()
```

2022-02-16 13:42 UTC, kakkoyun commented on pkg/profiler/profiler.go
> +				p.missingStacks.WithLabelValues("kernelstack").Inc()
```suggestion
				p.missingStacks.WithLabelValues("kernel").Inc()
```

2022-02-16 13:42 UTC, kakkoyun commented on pkg/profiler/profiler.go
> +				Name: "parca_agent_profiler_missing_stacks",
```suggestion
				Name: "parca_agent_profiler_missing_stacks_total",
```

FYI https://prometheus.io/docs/practices/naming/

2022-02-16 13:46 UTC, kakkoyun commented on pkg/profiler/profiler.go
> +				Name: "parca_agent_profiler_missing_stacks",
e. g. https://github.com/parca-dev/parca/blob/6e21eb3fb2b1d8e330545b4cdb42e1a9ff7d2005/pkg/metastore/cache.go#L65-L121

2022-02-16 16:58 UTC, kakkoyun approved these changes

2022-02-16 16:59 UTC, merged

2022-02-16 18:44 UTC, metalmatze commented
:rocket: