Update tests based on latest testdata changes
parca-dev/parca-agent pull request #2520
Opened 2024-02-19 09:09 UTC by Sylfrena

2024-02-19 12:19 UTC, kakkoyun requested changes
Hey, thanks for handling this!

Just a heads up, we need to tidy up a few things.

Also, I'm thinking it's better to use runtime.GOARCH wherever an arch is mentioned. That's unless we're aiming for a specific arch. If that's the plan, let's ensure the binary won't run on the wrong machine architecture.

2024-02-19 13:36 UTC, Sylfrena commented on pkg/elfreader/executable_test.go
> +	aslrEnabled, err := IsASLRElegible("../../testdata/out/amd64/basic-cpp")
I rebased all of it wrong 🥲

2024-02-22 10:24 UTC, kakkoyun reviewed
Looking good 🎉 

I'd be happy to merge it when the CI is green (except of course arm64 integration test)!

2024-08-08 08:47 UTC, brancz commented
Outdated since #2958

2024-08-08 08:47 UTC, closed without merging