pkg/agent: trigger batch before grpc message size overflow
parca-dev/parca-agent pull request #836
Opened 2022-09-24 08:21 UTC by heylongdacoder

Fixes: #203

Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>

2022-09-24 08:30 UTC, heylongdacoder commented
Hello, I don't have much experience on writing concurrent code, might make some mistake. Thanks for guidance in advance. :D

2022-10-10 14:22 UTC, kakkoyun requested changes
Looking great!

I think we can simplify this code and make it more maintainable. We can get rid of one of the mutex locking/unlocking and remove one of the channels if we can make `batch` method to receive a request (probably we should rename it to just `send` after this change). With this flow will be easier and less error prone. 

What do you think?

2022-10-10 14:22 UTC, kakkoyun commented on pkg/agent/batch_remote_write_client.go
> +	batchDone    chan struct{}
I think we can get rid of `batchDone` in here.

2022-10-10 14:22 UTC, kakkoyun commented on pkg/agent/batch_remote_write_client.go
>  func (b *BatchWriteClient) batch(ctx context.Context) error {
```suggestion
func batch(ctx context.Contextm, r *profilestorepb.WriteRawRequest) error {
```

This method can receive the request and by this way we can get rid of the lock in this method if I'm not mistaken. This method could also omit the write client as a receiver if it's the case.

2022-10-12 16:48 UTC, heylongdacoder commented
@kakkoyun thanks for the review and guidance! yes I need some help. I am not sure how would it works if we removed the `batchDone` channel. If we removed `batchDone`, I think there is a chance where `WriteRaw` function will continue to append data to the overflowed `writeRawRequest`(https://github.com/parca-dev/parca-agent/pull/836/files#diff-7276397f96515c11ca49f4f72de2237d63936ab985888a5a4fe07ccf8c371d42R166) before the `batch` function could send it. 

Currently I got another idea to avoid the creation of these `triggerBatch` and `batchDone` channels. Instead of a `writeRawRequest`, what about we create a slices of `writeRawRequest` and a `writeRawRequestIndex`? `WriteRaw` function will write to `writeRawRequest[writeRawRequestIndex]` and when the current one is going to be overflowed, then we write to `writeRawRequest[writeRawRequestIndex+1]`. Then the `batch` function either loop through the slices of `writeRawRequest` to fire gRPC request sequentially or create goroutine for each element to fire gRPC request. Do you think this would work and is this a better approach?

2024-08-08 08:48 UTC, brancz commented
Outdated since #2958 

We now use a totally new protocol that is apache-arrow based.

2024-08-08 08:48 UTC, closed without merging